name: artifact cicd

on:
  push:
    branches:
      - feat/artifact-learning

jobs:
  artifact-learning-steps:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: cache python virtual environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: linting check
        run: |
          source venv/bin/activate
          black --check .

      - name: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: output-dir

      - name: run python script.py
        run: python script.py > output-dir/script-output.txt

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: download-output-dir

      - name: show the content of downloaded artifact file
        run: |
          cat ./download-output-dir/python-output.txt
      

      
  