name: pull-request-schedule-workflow-dispatch

on:
  pull_request:

  schedule:
    - cron: '35 19 * * *' # Runs every day at 6:30 PM UTC (which is 12:00 AM IST)

  workflow_dispatch:
    inputs:
      environment:
        description: 'the environment to deploy to'
        required: true
        default: 'stg'
        type: choice
        options:
          - stg
          - prod
  
jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: run-script
        run: |
          python script.py