name: Python application

on:
  push:
    branches:
      - feat/artifact-learning

jobs:
  python-application:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: cache python virtual environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: create python virtual environment
        run: |
          pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: check python linting
        run: |
          source venv/bin/activate
          black .
          
      - name: Run python application
        run: |
          source venv/bin/activate
          python script.py -> output-dir/python-output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: pyhton-artifact
        with:
          name: upload_artifact
          path: output-dir
