name: Python application

on:
  push:
    branches:
      - main

jobs:
  python-application:
    runs-on: ubuntu-latest

    steps:
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Run python application
        run: |
          python script.py
