name: Use env secrate and variable

on:
  push:

jobs:
  use-secrate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ["dev", "stg", "prod"]

    environment: ${{ matrix.environment }}
    env:
      # NAME: ${{ secrets.NAME }}
      # ENV: prod
      VARIABLE: ${{ vars.ENV_VARIABLE }}

    steps:
      - name: Print secrets
        run: |
          echo "${{ secrets.NAME }}"

      - name: Print env variable
        run: |
          echo "variable name ${{ vars.ENV_VARIABLE }}"
          echo "env name ${{ secrets.ENV_NAME }}"

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-varsion: "3.8"

      - name: Set env using github_env
        run: |
          echo "github_env_variable_1=dynamically environment set to github_env" >> $GITHUB_ENV
          echo "github_env_variable_2=second environment variable" >> $GITHUB_ENV

      - name: Set env using linux export command
        run: |
          export export1="set value to export 1"
          export export2="set value to export 2"

      - name: run python script
        run: |
          python script1.py